version: '3'

networks:
  backend:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./projects:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    depends_on:
      - php-7.4
      - db
    environment:
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
      - backend

  db:
    image: postgres:alpine
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dump:/dump
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
    networks:
        - backend
    container_name: db

  php-7.4:
    build:
      context: ./php-workspace
      dockerfile: Dockerfile
      args:
        DOCKER_PHP_VERSION: '7.4'
        DOCKER_PHP_ENABLE_XDEBUG: ${DOCKER_PHP_ENABLE_XDEBUG}
        TZ: ${WORKSPACE_TIMEZONE}
    working_dir: /var/www
    container_name: php-7.4
    volumes:
      - ./.ssh:/home/www-data/.ssh
      - ./projects:/var/www
      - ./php-ini/7.4/php.ini:/usr/local/etc/php/php.ini
      - ./php-workers/7.4/supervisor.d:/etc/supervisor.d
    ports:
      - "${PHP_7_4_PORT}:9000"
    networks:
      - backend
    extra_hosts:
      - 'uoai.loc:127.0.0.1'
      - 'maslov.loc:127.0.0.1'